pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        script {
          // Install dependencies and start the Node.js app
          sh '''
            npm install
            npm start &
            sleep 5
            curl http://localhost:3000
          '''
        }
      }
    }
  }
}
